TARGETS = example
PREFIX = $(shell echo `pwd`)/pkg/

.PHONY: all clean package

package: all
 cd pkg; fakeroot -- chown -R root:root * && tar czf ../modules.tgz *

all:
 for T in $(TARGETS); do  \
  ${MAKE} -C $$T;  \
  ${MAKE} -C $$T PREFIX=$(PREFIX) install;  \
 done;

clean:
 for T in $(TARGETS); do  \
  ${MAKE} -C $$T clean; \
 done
 rm -rf modules.tgz pkg

